### ISSUE TITLE
./ss-web-manager  errot

### ISSUE THREAD

**Issue by mimta** [linexjlin/ss-web-manager#5]
I just installed ss-web-manager, but when I want to run it I got this error. any help?!

```
./ss-web-manager 
panic: invalid character '"' after object key:value pair

goroutine 1 [running]:
main.checkError(0x890a00, 0xc4201162c0)
	/root/ss-web-manager/mis.go:11 +0x4a
main.loadConf(0x846290, 0xd, 0xab2420)
	/root/ss-web-manager/conf.go:28 +0x135
main.main()
	/root/ss-web-manager/main.go:8 +0x46
```

Thanks

**Comment by linexjlin** [comment]
This was a test project. It is no longer maintain. Here is a alternative one 
https://github.com/sendya/shadowsocks-panel/tree/v0.4 
Thanks for your response.
